### ISSUE TITLE
Getting error while using template with react and jsdoc

### ISSUE THREAD

**Issue by 0sikarwar** [SoftwareBrothers/better-docs#131]
Getting the following error whenever i tried to add `"template": "node_modules/better-docs"` in **opts** of my jsdoc.conf.json

`yarn run v1.12.3
$ jsdoc -c jsdoc.conf.json
Generating entry file for "components" plugin
Bundling components
running: NODE_ENV=development parcel build docs/entry.js --out-dir docs/build
/bin/sh: parcel: command not found

/Users/gyanendersingh/bento-payments-ui/node_modules/better-docs/bundler.js:91
    throw error
    ^

Error: Command failed: NODE_ENV=development parcel build docs/entry.js --out-dir docs/build
/bin/sh: parcel: command not found

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at bundle (/Users/gyanendersingh/bento-payments-ui/node_modules/better-docs/bundler.js:86:5)
    at Object.exports.publish (/Users/gyanendersingh/bento-payments-ui/node_modules/better-docs/publish.js:717:3)
    at Object.module.exports.cli.generateDocs (/Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/cli.js:441:39)
    at Object.module.exports.cli.processParseResults (/Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/cli.js:392:24)
    at module.exports.cli.main (/Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/cli.js:235:18)
    at Object.module.exports.cli.runCommand (/Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/cli.js:186:9)
    at /Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/Users/gyanendersingh/bento-payments-ui/node_modules/jsdoc/jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 70 61 72 63 65 6c 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 65637,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 70 61 72 63 65 6c 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Here is the current config i am using
**jsdoc.conf.json**
`{
  "tags": {
    "allowUnknownTags": true,
    "dictionaries": ["jsdoc", "closure"]
  },
  "source": {
    "include": ["src"],
    "includePattern": ".+\\.js(doc|x)?$",
    "excludePattern": "(^|\\/|\\\\)_"
  },
  "plugins": ["plugins/markdown", "better-docs/component", "better-docs/category"],
  "templates": {
    "better-docs": {
      "name": "My React components"
    }
  },
  "opts": {
    "destination": "docs",
    "recurse": true,
    "readme": "README.md"
  }
}
`

i also tried using `"template": "./node_modules/better-docs"`

**CMD used to run docs**
`"docs": "jsdoc -c jsdoc.conf.json"`

versions from my package.json
"react": "^17.0.1"
"jsdoc": "^3.6.6"

**Comment by przemyslaw-szejna-sb** [comment]
Please use `2.4.1` version of better-docs
