### ISSUE TITLE
Cannot use better docs with vue typescript single file components

### ISSUE THREAD

**Issue by iAmNotDrunk** [SoftwareBrothers/better-docs#133]
When I specify that I want to use typescript like this:

`<script lang="ts">
/**
 * Most top level component
 * @component
 * @example
 * <App />
 */
export default {}
</script>`

I get this error msg when I build when I try to build the documentation:

/home/thachlp/frontend-test/node_modules/better-docs/component.js:11
      e.source = script[1]
                       ^

TypeError: Cannot read property '1' of null
    at Parser.beforeParse (/home/thachlp/frontend-test/node_modules/better-docs/component.js:11:24)
    at Parser.emit (events.js:326:22)
    at Parser._parseSourceCode (/home/thachlp/frontend-test/node_modules/jsdoc/lib/jsdoc/src/parser.js:288:18)
    at Parser.parse (/home/thachlp/frontend-test/node_modules/jsdoc/lib/jsdoc/src/parser.js:202:22)
    at Object.module.exports.cli.parseFiles (/home/thachlp/frontend-test/node_modules/jsdoc/cli.js:365:46)
    at module.exports.cli.main (/home/thachlp/frontend-test/node_modules/jsdoc/cli.js:234:18)
    at Object.module.exports.cli.runCommand (/home/thachlp/frontend-test/node_modules/jsdoc/cli.js:186:9)
    at /home/thachlp/frontend-test/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/home/thachlp/frontend-test/node_modules/jsdoc/jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

I believe it is because of the regular expression in the component.js file in better docs that says:
    `var script = e.source.match(new RegExp('<script>(.*?)</script>', 's'))`

It worked fine for me when I added lang="ts" to the `<script>` tag

I am using better docs version 2.3.2

**Comment by oz-** [comment]
Same here...

**Comment by Elaniobro** [comment]
I am using Vuejs, but I also do not see any components being rendered as part of the docs.

using `"better-docs": "^2.3.2",`

here is my `jsdoc.config`
```js
{
	"jsdoc-vuejs": {
		"followImports": true
	},
	"opts": {
      "encoding": "utf8",
      "destination": "docs/",
      "recurse": true,
      "verbose": true,
      "readme": "./readme.md",
      "template": "node_modules/better-docs"
	},
	"plugins": [
          "better-docs/component",
          "better-docs/category",
	  "better-docs/typescript"
	],
	"source": {
		"include": ["."],
		"exclude": ["node_modules"],
		"includePattern": "\\.(jsx|js|ts|tsx)$",
		"excludePattern": "\\.(spec.ts)$"
	},
	"tags": {
      	"allowUnknownTags": true,
		"dictionaries": ["jsdoc"]
	},
	"templates": {
        "search": true,
        "default": {
		"staticFiles": {
            	  "include": ["./static/"]
        	}
        },
        "better-docs": {
            "name": "Documentation",
            "logo": "images/logo.png",
            "title": "", // HTML title
            "css": "style.css",
        }
    }
}

```

**Comment by Elaniobro** [comment]
Like wise, I too am using `"better-docs": "^2.3.2",`

However, even trying the solution that @linhphandk suggested did not work for me, that being:
`var script = e.source.match(new RegExp('<script lang="ts">(.*?)</script>', 's'))`


here is my `jsdoc.config` in its entirety:

```js
{
  "jsdoc-vuejs": {
    "followImports": true
  },
  "opts": {
  "encoding": "utf8",
  "destination": "docs/",
  "recurse": true,
  "verbose": true,
  "readme": "./readme.md",
  "template": "node_modules/better-docs"
  },
  "plugins": [
    "better-docs/component",
    "better-docs/category",
    "better-docs/typescript"
  ],
  "source": {
    "include": ["."],
    "exclude": ["node_modules"],
    "includePattern": "\\.(vue|js|ts)$",
    "excludePattern": "\\.(spec.ts)$"
  },
  "tags": {
    "allowUnknownTags": true,
    "dictionaries": ["jsdoc"]
  },
  "templates": {
    "search": true,
    "default": {
    "staticFiles": {
        "include": ["./static/"]
      }
    },
    "better-docs": {
      "name": "Documentation",
      "logo": "images/logo.png",
      "title": "", // HTML title
      "css": "style.css",
    }
  }
}
```

**Comment by bvargin-dev** [comment]
Hi,

It worked, but it was painful (https://github.com/SoftwareBrothers/better-docs/issues/55)

I wish it could help you.
