### ISSUE TITLE
Compiling error: private class features

### ISSUE THREAD

**Issue by massimiliamanto74** [SoftwareBrothers/better-docs#179]
Hi all,
I am try to use a private class feature like this:

`  readonly #MAP_CLASSES = {
    google: GoogleMap,
    osm: OsmMap,
    kakao: KakaoMap,
    baidu: BaiduMap,
  };
`

but when I try to compile the docs I have an error:

`
ERROR: Unable to parse /...../src/classes/file.ts: Private name #MAP_CLASSES is not defined. (599:19)
`

this is a complete log error:
`

- 0 info it worked if it ends with ok
- 1 verbose cli [
- 1 verbose cli   '/.../.nvm/versions/node/v14.18.1/bin/node',
- 1 verbose cli   '/.../.nvm/versions/node/v14.18.1/bin/npm',
- 1 verbose cli   'run',
- 1 verbose cli   'docs'
- 1 verbose cli ]
- 2 info using npm@6.14.15
- 3 info using node@v14.18.1
- 4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
- 5 info lifecycle onthemap-js-api@1.0.0~predocs: onthemap-js-api@1.0.0
- 6 info lifecycle onthemap-js-api@1.0.0~docs: onthemap-js-api@1.0.0
- 7 verbose lifecycle onthemap-js-api@1.0.0~docs: unsafe-perm in lifecycle true
- 8 verbose lifecycle onthemap-js-api@1.0.0~docs: PATH: /.../.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/.../Documents/lavoro/OTM/onthemap-experience-jsapi/node_modules/.bin:/..../.nvm/versions/node/v14.18.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/.../.nvm/versions/node/v14.18.1/bin
- 9 verbose lifecycle onthemap-js-api@1.0.0~docs: CWD: /Users/.../Documents/lavoro/....
- 10 silly lifecycle onthemap-js-api@1.0.0~docs: Args: [
- 10 silly lifecycle   '-c',
- 10 silly lifecycle   'copyfiles -f src/docs-src/img/*.png docs/img/ && copyfiles -f src/docs-src/css/*.css docs/css/ && jsdoc -c jsdoc.json'
- 10 silly lifecycle ]
- 11 silly lifecycle onthemap-js-api@1.0.0~docs: Returned: code: 1  signal: null
- 12 info lifecycle onthemap-js-api@1.0.0~docs: Failed to exec docs script
- 13 verbose stack Error: onthemap-js-api@1.0.0 docs: `copyfiles -f src/docs-src/img/*.png docs/img/ && copyfiles -f src/docs-src/css/*.css docs/css/ && jsdoc -c jsdoc.json`
- 13 verbose stack Exit status 1
- 13 verbose stack     at EventEmitter.<anonymous> (/Users/.../.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
- 13 verbose stack     at EventEmitter.emit (events.js:400:28)
- 13 verbose stack     at ChildProcess.<anonymous> (/Users/.../.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
- 13 verbose stack     at ChildProcess.emit (events.js:400:28)
- 13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
- 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
- 14 verbose pkgid onthemap-js-api@1.0.0
- 15 verbose cwd /Users/..../Documents/lavoro/OTM/onthemap-experience-jsapi
- 16 verbose Darwin 21.1.0
- 17 verbose argv "/Users/.../.nvm/versions/node/v14.18.1/bin/node" "/Users/..../.nvm/versions/node/v14.18.1/bin/npm" "run" "docs"
- 18 verbose node v14.18.1
- 19 verbose npm  v6.14.15
- 20 error code ELIFECYCLE
- 21 error errno 1
- 22 error onthemap-js-api@1.0.0 docs: `copyfiles -f src/docs-src/img/*.png docs/img/ && copyfiles -f src/docs-src/css/*.css docs/css/ && jsdoc -c jsdoc.json`
- 22 error Exit status 1
- 23 error Failed at the onthemap-js-api@1.0.0 docs script.
- 23 error This is probably not a problem with npm. There is likely additional logging output above.
- 24 verbose exit [ 1, true ]

`

I have tried to search a fix but I did not find anythings for help me. 
Has some one try a fix?

**Comment by przemyslaw-szejna-sb** [comment]
Please try new version `2.4.1`
