### ISSUE TITLE
@component: Bad character escape sequence error on windows 10

### ISSUE THREAD

**Issue by fhenderson** [SoftwareBrothers/better-docs#43]
When I add the tag @component in a React functional component description header and I ran the documentation generation I am getting the following error. Any idea of how the generated PATH got inserted `\` in it

```
D:\git\nirvana\ui>yarn docs
yarn run v1.17.3
$ jsdoc -c jsdoc.conf.json
Generating entry file for "components" plugin
Bundling components
running: parcel build docs/entry.js --out-dir docs/build
×  D:\git\nirvana\ui\docs\entry.js:12:54: Bad character escape sequence (12:54)
  10 |
  11 |
> 12 |       import ReactWrapper from '../../D:\git\nirvana\ui\node_modules\better-docs/lib/react-wrapper.js';
     |                                                      ^
  13 |
  14 |       window.React = React;
  15 |

D:\git\nirvana\ui\node_modules\better-docs\bundler.js:83
    throw error
    ^

Error: Command failed: parcel build docs/entry.js --out-dir docs/build
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at bundle (D:\git\nirvana\ui\node_modules\better-docs\bundler.js:78:5)
    at Object.exports.publish (D:\git\nirvana\ui\node_modules\better-docs\publish.js:655:5)
    at Object.module.exports.cli.generateDocs (D:\git\nirvana\ui\node_modules\jsdoc\cli.js:441:39)
    at Object.module.exports.cli.processParseResults (D:\git\nirvana\ui\node_modules\jsdoc\cli.js:392:24)
    at module.exports.cli.main (D:\git\nirvana\ui\node_modules\jsdoc\cli.js:235:18)
    at Object.module.exports.cli.runCommand.cb [as runCommand] (D:\git\nirvana\ui\node_modules\jsdoc\cli.js:186:9)
    at D:\git\nirvana\ui\node_modules\jsdoc\jsdoc.js:93:9
    at Object.<anonymous> (D:\git\nirvana\ui\node_modules\jsdoc\jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Korhm** [comment]
I can confirm that fix from DoubleU23 is working.

**Comment by apolopena** [comment]
I still get the issue using "better-docs": "1.4.7" on Windows 10. Looks like the pathing to the component is erroneous. Here is the interesting part of the stack trace:
```
Bundling components
running: parcel build docs\/entry.js --out-dir docs\/build
×  C:\Users\penav\visual-studio-projects\apolopenadotcom\docs\entry.js:25:25: Cannot resolve dependency '../../C:Userspenav
                                                                                                                           isual-studio-projectsapolopenadotcomsrccomponentsSmartCaption.js' at 'C:\Users\penav\visual-st
udio-projects\C:Userspenav
                          isual-studio-projectsapolopenadotcomsrccomponentsSmartCaption.js'
  23 |     import './styles/iframe.css';
  24 |
> 25 |   import Component0 from '../../C:\Users\penav\visual-studio-projects\apolopenadotcom\src\components\SmartCaption.js';
     |                         ^
  26 | reactComponents['SmartCaption'] = Component0;

C:\Users\penav\visual-studio-projects\apolopenadotcom\node_modules\better-docs\bundler.js:83
    throw error
    ^

Error: Command failed: parcel build docs\/entry.js --out-dir docs\/build
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at bundle (C:\Users\penav\visual-studio-projects\apolopenadotcom\node_modules\better-docs\bundler.js:78:5)
```

**Comment by apolopena** [comment]
The fix from DoubleU23 has not been implemented. Would be nice to get this in.

**Comment by maamve** [comment]
Please we need this!
