### ISSUE TITLE
Windows parcel error

### ISSUE THREAD

**Issue by pacocom** [SoftwareBrothers/better-docs#66]
It has two parcel error:

1.
```
Parsing C:\Users\Francisco\Documents\baikal-global\developers\src\components\SearchBar\index.tsx ...
Generating output files...
Generating entry file for "components" plugin
Bundling components
running: parcel build jsdoc\/entry.js --out-dir jsdoc\/build
"parcel" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\bundler.js:83
    throw error
    ^

Error: Command failed: parcel build jsdoc\/entry.js --out-dir jsdoc\/build
"parcel" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at bundle (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\bundler.js:78:5)
    at Object.exports.publish (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\publish.js:655:5)
    at Object.module.exports.cli.generateDocs (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:441:39)
    at Object.module.exports.cli.processParseResults (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:392:24)
    at module.exports.cli.main (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:235:18)
    at Object.module.exports.cli.runCommand (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:186:9)
    at C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\jsdoc.js:93:9
    at Object.<anonymous> (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 22 70 61 72 63 65 6c 22 20 6e 6f 20 73 65 20 72 65 63 6f 6e 6f 63 65 20 63 6f 6d 6f 20 75 6e 20 63 6f 6d 61 6e 64 6f 20 69 6e 74 65 72 6e 6f 20 6f 20 ... 52 more bytes>
  ],
  pid: 14008,
  stdout: <Buffer >,
  stderr: <Buffer 22 70 61 72 63 65 6c 22 20 6e 6f 20 73 65 20 72 65 63 6f 6e 6f 63 65 20 63 6f 6d 6f 20 75 6e 20 63 6f 6d 61 6e 64 6f 20 69 6e 74 65 72 6e 6f 20 6f 20 ... 52 more bytes>
}
```
You need to add parcel as dependency.

2.
```
×  C:\Users\Francisco\Documents\baikal-global\developers\jsdoc\entry.js:25:25: Cannot resolve dependency '../../C:UsersFranciscoDocumentaikal-globaldeveloperssrccomponentsFilterResultindex.tsx' at 'C:\Users\Francisco\Documents\baikal-global\C:UsersFranciscoDocumentaikal-globaldeveloperssrccomponentsFilterResultindex.tsx'
  23 |     import './styles/iframe.css';
  24 |
> 25 |   import Component0 from '../../C:\Users\Francisco\Documents\baikal-global\developers\src\components\FilterResult\index.tsx';
     |                         ^
  26 | reactComponents['FilterResult'] = Component0;
  27 |
  28 | import Component1 from '../../C:\Users\Francisco\Documents\baikal-global\developers\src\components\SearchBar\index.tsx';

C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\bundler.js:83
    throw error
    ^

Error: Command failed: parcel build jsdoc/entry.js --out-dir jsdoc/build
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at bundle (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\bundler.js:78:5)
    at Object.exports.publish (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\better-docs\publish.js:655:5)
    at Object.module.exports.cli.generateDocs (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:441:39)
    at Object.module.exports.cli.processParseResults (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:392:24)
    at module.exports.cli.main (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:235:18)
    at Object.module.exports.cli.runCommand (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\cli.js:186:9)
    at C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\jsdoc.js:93:9
    at Object.<anonymous> (C:\Users\Francisco\Documents\baikal-global\developers\node_modules\jsdoc\jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer c3 97 20 20 43 3a 5c 55 73 65 72 73 5c 46 72 61 6e 63 69 73 63 6f 5c 44 6f 63 75 6d 65 6e 74 73 5c 62 61 69 6b 61 6c 2d 67 6c 6f 62 61 6c 5c 64 65 76 ... 682 more bytes>,
    <Buffer >
  ],
  pid: 16608,
  stdout: <Buffer c3 97 20 20 43 3a 5c 55 73 65 72 73 5c 46 72 61 6e 63 69 73 63 6f 5c 44 6f 63 75 6d 65 6e 74 73 5c 62 61 69 6b 61 6c 2d 67 6c 6f 62 61 6c 5c 64 65 76 ... 682 more bytes>,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
```

You can fix with https://stackoverflow.com/questions/59809560/better-docs-creates-entry-js-file-incorrectly.

**Comment by vis97c** [comment]
It should be fixed in #46 , i also did some changes to better support windows in #96 but for you ploblem i think that updating to the latest version should be enough.
