### ISSUE TITLE
@component, Parcel: error with Meteor package import

### ISSUE THREAD

**Issue by OliverColeman** [SoftwareBrothers/better-docs#69]
I have a Meteor app, and I'm getting this error when trying to document a React component with the @component tag for component files that import a Meteor package.  Not sure whether this is an issue with something I'm doing, or better-docs, or Parcel...

```
unning: parcel build dev/docs/entry.js --out-dir dev/docs/build
🚨  /home/data/work/airsight/workspace/code/axldm/imports/ui/components/MaskEditor/Annotation.jsx:6:32: Cannot resolve dependency 'meteor/react-meteor-data'
  4 | import RK from 'react-konva';
  5 | import { Point, Polygon, Segment } from '@flatten-js/core'; 
> 6 | import { createContainer } from 'meteor/react-meteor-data';
    |                                ^
  7 | 
  8 | import RKMultiPolygon from './RKMultiPolygon';
  9 | import AnnotationInstanceLabels from './AnnotationInstanceLabels';

/home/data/work/airsight/workspace/code/axldm/node_modules/better-docs/bundler.js:83
    throw error
    ^

Error: Command failed: parcel build dev/docs/entry.js --out-dir dev/docs/build
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at bundle (/home/data/work/airsight/workspace/code/axldm/node_modules/better-docs/bundler.js:78:5)
    at Object.exports.publish (/home/data/work/airsight/workspace/code/axldm/node_modules/better-docs/publish.js:655:5)
    at Object.module.exports.cli.generateDocs (/home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/cli.js:441:39)
    at Object.module.exports.cli.processParseResults (/home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/cli.js:392:24)
    at module.exports.cli.main (/home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/cli.js:235:18)
    at Object.module.exports.cli.runCommand.cb [as runCommand] (/home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/cli.js:186:9)
    at /home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/home/data/work/airsight/workspace/code/axldm/node_modules/jsdoc/jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Comment by wojtek-krysiak** [comment]
It is a parcel error: please try to run `parcel build dev/docs/entry.js --out-dir dev/docs/build` manually and see what is the error and post it here.

**Comment by julius1986** [comment]
I have the same error, when I try to start  "parcel build dev/docs/entry.js --out-dir dev/docs/build", the system tells me that I have problems with scripts and gives me the link https:/go.microsoft.com/fwlink/?LinkID=135170

**Comment by wojtek-krysiak** [comment]
can you post the stack trace?

**Comment by ShaggyKris** [comment]
@wojtek-krysiak I am having the same issue. 

```
running: NODE_ENV=development parcel build docs/entry.js --out-dir docs/build
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
🚨  /Users/user/WebstormProjects/Meteor_Project/imports/ui/components/dashboards/DashboardContainer.jsx:4:28: Cannot resolve dependency 'meteor/react-meteor-data'
  2 | import { loadCSS } from "fg-loadcss";
  3 | import { Meteor } from "meteor/meteor";
> 4 | import { withTracker } from "meteor/react-meteor-data";
    |                            ^
  5 | import React, { Component } from "react";
  6 | import MetaTags from "react-meta-tags";
  7 | import {

/Users/user/WebstormProjects/Meteor_Project/node_modules/better-docs/bundler.js:91
    throw error
    ^

Error: Command failed: NODE_ENV=development parcel build docs/entry.js --out-dir docs/build
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at bundle (/Users/user/WebstormProjects/Meteor_Project/node_modules/better-docs/bundler.js:86:5)
    at Object.exports.publish (/Users/user/WebstormProjects/Meteor_Project/node_modules/better-docs/publish.js:717:3)
    at Object.module.exports.cli.generateDocs (/Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/cli.js:441:39)
    at Object.module.exports.cli.processParseResults (/Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/cli.js:392:24)
    at module.exports.cli.main (/Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/cli.js:235:18)
    at Object.module.exports.cli.runCommand (/Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/cli.js:186:9)
    at /Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/Users/user/WebstormProjects/Meteor_Project/node_modules/jsdoc/jsdoc.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer f0 9f 9a a8 20 20 2f 55 73 65 72 73 2f 6b 72 69 73 74 6f 66 65 72 70 65 72 76 69 6e 2f 57 65 62 73 74 6f 72 6d 50 72 6f 6a 65 63 74 73 2f 57 61 67 67 ... 423 more bytes>,
    <Buffer 42 72 6f 77 73 65 72 73 6c 69 73 74 3a 20 63 61 6e 69 75 73 65 2d 6c 69 74 65 20 69 73 20 6f 75 74 64 61 74 65 64 2e 20 50 6c 65 61 73 65 20 72 75 6e ... 39 more bytes>
  ],
  pid: 54829,
  stdout: <Buffer f0 9f 9a a8 20 20 2f 55 73 65 72 73 2f 6b 72 69 73 74 6f 66 65 72 70 65 72 76 69 6e 2f 57 65 62 73 74 6f 72 6d 50 72 6f 6a 65 63 74 73 2f 57 61 67 67 ... 423 more bytes>,
  stderr: <Buffer 42 72 6f 77 73 65 72 73 6c 69 73 74 3a 20 63 61 6e 69 75 73 65 2d 6c 69 74 65 20 69 73 20 6f 75 74 64 61 74 65 64 2e 20 50 6c 65 61 73 65 20 72 75 6e ... 39 more bytes>
}

```

After running `parcel build dev/docs/entry.js --out-dir dev/docs/build`, I get the following:

```
user@MacBook-Pro-15 Meteor_Project % parcel build dev/docs/entry.js --out-dir dev/docs/build
🚨  No entries found.
    at Bundler.bundle (/usr/local/lib/node_modules/parcel-bundler/src/Bundler.js:275:17)
user@MacBook-Pro-15 Meteor_Project % parcel build docs/entry.js --out-dir docs/build             
🚨  /Users/user/WebstormProjects/Meteor_Project/imports/ui/components/dashboards/Dashboard.jsx:6:23: Cannot resolve dependency 'meteor/meteor'
  4 | import { Grid, IconButton, Paper, withStyles } from "@material-ui/core";
  5 | import HelpIcon from "@material-ui/icons/Help";
> 6 | import { Meteor } from "meteor/meteor";
    |                       ^
  7 | import React, { Component } from "react";
  8 | import MetaTags from "react-meta-tags";
  9 | import { toast } from "react-toastify";
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`

```

**Comment by stephanie-saretsky** [comment]
Did anyone figure out a workaround for this? I am also having the same issue and am getting the same `No entries found` as @ShaggyKris.
